spring.application.name=financial-control


# DATASOURCE - SUPABASE
spring.datasource.url=changeId
spring.datasource.username=postgres
spring.datasource.password=changeId
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


supabase.url=changeId
supabase.service-role-key=changeId
supabase.jwtSecret=changeId

spring.batch.jdbc.initialize-schema=never
server.port=8080
